version: "3.9"
services:
  db:
    image: postgres:15
    container_name: odoo-staging-db
    restart: unless-stopped
    environment:
      POSTGRES_DB: "odoo_staging"
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
    volumes:
      - odoo_staging_pgdata:/var/lib/postgresql/data

  odoo:
    image: odoo:16
    container_name: odoo-staging
    depends_on:
      - db
    restart: unless-stopped
    env_file:
      - ../../.env.staging
    volumes:
      - ../../odoo/config/odoo.staging.conf:/etc/odoo/odoo.conf:ro
      - odoo_staging_data:/var/lib/odoo
    ports:
      - "8069:8069"

volumes:
  odoo_staging_pgdata:
  odoo_staging_data:
